spring:
  cloud:
    config:
      uri: http://localhost:8888
      
  application:
    name: ORDER-API-GATEWAY
    
server:
  port: 8080
  
zuul:
  routes:
    startpage:
     path: /**
     url: http://localhost:8080
    CUSTOMER_MS:
     path: /ibm/**
    OREDER_MS:
      path: /ibm/**
   